name: 🐛 Report a Bug
description: Create a report to help us improve the Titanium Atom Package
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: What do you expect to happen
    validations:
      required: true
  - type: textarea
    attributes:
      labels: Environment
      description: Make sure to include all relevant information. SDK version, CLI version, Atom version etc.
    validations:
      required: true
  - type: textarea 
    attributes:
      labels: Logs
      description: Any logs that might help us diagnose the issue
