name: 💡 Propose a Feature
description: Suggest a new feature or improvement for atom-appcelerator-titanium
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Describe the problem you're solving
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternative solutions you've considered
    validations:
      required: true
